[[isa_l]]
arch = "aarch64"
git-tree-sha1 = "1ba2ae9a9536588d479c0c85d243ed30c42ca3b0"
libc = "glibc"
os = "linux"

    [[isa_l.download]]
    sha256 = "52c3ab5bfa99c1fe7e7bc4d32068491ab20db93de26c684f7c85278dd4bf2e1c"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.aarch64-linux-gnu.tar.gz"
[[isa_l]]
arch = "aarch64"
git-tree-sha1 = "7116de7dfe7d73ca82502401d67a008daa7d1bb2"
libc = "musl"
os = "linux"

    [[isa_l.download]]
    sha256 = "230c701509b407aa1f766fc7cddb8f788be5b857ba1db7f5a09c37c7d64a0a73"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.aarch64-linux-musl.tar.gz"
[[isa_l]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d9393bf14a99855fb0b7fb6b0b3d59c2aa7d41d"
libc = "glibc"
os = "linux"

    [[isa_l.download]]
    sha256 = "be8037d590d580ced563cf9c8503a3bf7bb02e29c541791125f90dd976f51497"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.armv6l-linux-gnueabihf.tar.gz"
[[isa_l]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "23007b681352077f087593f7bf250c915743f031"
libc = "musl"
os = "linux"

    [[isa_l.download]]
    sha256 = "0466cfe44f2496a7f5b1df9c0d75f56b7ddad79dd3c460c97b0b229336213e72"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.armv6l-linux-musleabihf.tar.gz"
[[isa_l]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebb78ed7a4f5f50edb88e7b64d0c09e161ed12d6"
libc = "glibc"
os = "linux"

    [[isa_l.download]]
    sha256 = "d00aa9ea4239bc6f11fe7234f48ff1f10c415bc346ba8d569f9148c851c99a96"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.armv7l-linux-gnueabihf.tar.gz"
[[isa_l]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6f9f015af87f685f732eb8c1f8c70a85e683ed81"
libc = "musl"
os = "linux"

    [[isa_l.download]]
    sha256 = "828d294cd0ac69a61e30b828d19b1284c7b5d9977c322ebe13786a607502883e"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.armv7l-linux-musleabihf.tar.gz"
[[isa_l]]
arch = "powerpc64le"
git-tree-sha1 = "c74e48b05ab932a8441da4360cb35eef09326751"
libc = "glibc"
os = "linux"

    [[isa_l.download]]
    sha256 = "a03e24d860d2b73d2f44b676879f8579ec705704808ed5aceb1d31315121bc1d"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.powerpc64le-linux-gnu.tar.gz"
[[isa_l]]
arch = "x86_64"
git-tree-sha1 = "7422ce03df4939e0c39aba89aa554717e96b302d"
os = "macos"

    [[isa_l.download]]
    sha256 = "7db11bb099abe76f93a8e323c91746c646911efa43c8774bcbdbf587664474de"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.x86_64-apple-darwin.tar.gz"
[[isa_l]]
arch = "x86_64"
git-tree-sha1 = "070dbf4944ebe3a2dac2dde15879c60026e416b2"
libc = "glibc"
os = "linux"

    [[isa_l.download]]
    sha256 = "921b13b7dac9613d6bf4b9c1cb3b72aadd99de10aa843c68f4a41c5ba39e6aee"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.x86_64-linux-gnu.tar.gz"
[[isa_l]]
arch = "x86_64"
git-tree-sha1 = "2f9d9d5fe5757a84007f5738703947dbed248866"
libc = "musl"
os = "linux"

    [[isa_l.download]]
    sha256 = "47ca3943b8f70e0b176275ddff8c88682b973451ff5e9d4b600899acdd853199"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.x86_64-linux-musl.tar.gz"
[[isa_l]]
arch = "x86_64"
git-tree-sha1 = "c7da3b5e7e1a6f8cdb2741fdff6ba7877b114e70"
os = "freebsd"

    [[isa_l.download]]
    sha256 = "755c65384963472f5e763268ef460f2103e2a1265f7af3941c94f018386799b9"
    url = "https://github.com/JuliaBinaryWrappers/isa_l_jll.jl/releases/download/isa_l-v2.31.0+0/isa_l.v2.31.0.x86_64-unknown-freebsd.tar.gz"
